# Generated by Django 5.2.17 on 2026-09-20 18:18

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("film", "Film"), ("game", "Game"), ("album", "Album")],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("release_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("combined_text", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
                ),
                ("embedding_model", models.CharField(blank=True, default="", max_length=100)),
                ("embedding_dim", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["media_type"], name="item_media_type_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("embedding__isnull", True),
                                ("embedding_dim__isnull", True),
                                ("embedding_model", ""),
                            ),
                            models.Q(
                                ("embedding__isnull", False),
                                ("embedding_dim__isnull", False),
                                models.Q(("embedding_model", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="item_embedding_has_model_and_dim",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=100)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ids",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"), name="externalid_source_external_id_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("vote_count", models.PositiveIntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "source"), name="score_item_source_uniq"
                    )
                ],
            },
        ),
    ]
