# Generated by Django 5.2.17 on 2026-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkippedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=100)),
                ("reason", models.CharField(max_length=50)),
                ("checked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="skippedrecord_source_external_id_uniq",
                    )
                ],
            },
        ),
    ]
