# Generated by Django 5.2.17 on 2026-09-21 16:49

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_skippedrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text_hash", models.CharField(max_length=64)),
                ("embedding_model", models.CharField(max_length=100)),
                ("embedding_dim", models.PositiveSmallIntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("text_hash", "embedding_model", "embedding_dim"),
                        name="queryembedding_text_model_dim_uniq",
                    )
                ],
            },
        ),
    ]
