# Generated by Django 5.2.17 on 2026-09-22 09:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_queryembedding"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("combined_text", config="english"),
                name="item_combined_text_gin",
            ),
        ),
    ]
